### ISSUE TITLE
List this library on DuckDB docs site

### ISSUE THREAD

**Issue by nileshtrivedi** [mmzeeman/educkdb#25]
I think this library should be listed on this page: https://duckdb.org/docs/api/overview

**Comment by mmzeeman** [comment]
Busy with updating it to v1.1.3. I will try to get it listed after I finish that. The current library uses an unstable release from a couple of years ago.

**Comment by mmzeeman** [comment]
Added the library to the overview page. Here is the PR. https://github.com/duckdb/duckdb-web/pull/4134

**Comment by mmzeeman** [comment]
Merged... Thanks for pointing me to the list.
